console.log("************Step 1************");
var myFullName = " My full Name : Ajim Shikalgar";
console.log(myFullName);
var myFullName = "My full Name with middle name is : Ajim Rajekhan shikalgar ";
console.log(myFullName);
console.log("************Step 2**************");
var myLove = "I love only JS ";
console.log(myLove);
console.log("************Step 3**************");
var firstName = "First Name: Ajim";
console.log(firstName);
var lastname = "Last Name: Shikalgar";
console.log(lastname);
var age = "Age: 23";
console.log(age);
var address = "Address: at post Yelavi Tal. Tasgaon dist. Sangli";
console.log(address);
var pinCode = "PinCode: 416319";
console.log(pinCode);
var gender = "Gender: Male";
console.log(gender);
var isMarried = "Married: No";
console.log(isMarried);